project:
  type: website
  output-dir: _site

website:
  title: "Site Julio Vargas"
  navbar:
    left:
    - href: assignment04-juliocesarvg_sol.html
      text: Inicio

format:
  html:
    theme: cosmo
